name: Upload Document as Artifact

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'resume.md'
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'resume.pdf'
          path: .
#           path: ${{ steps.publish-document.outputs.pdf }}
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ steps.publish-document.outputs.pdf }}
          host: ${{ secrets.MY_SERVER_DOMAIN }}
          remote: ${{ secrets.MY_SERVER_HTML_ROOT }}
          port: ${{ secrets.MY_SERVER_SSH_PORT }}
          user: ${{ secrets.MY_SERVER_SSH_USER }}
          key: ${{ secrets.MY_PC_PRIVATE_KEY }}
